### ISSUE TITLE
Unable to connect to the azure monitor API

### ISSUE THREAD

**Issue by aravindrd23** [grafana/azure-monitor-datasource#49] opened 2018-04-11 17:00 UTC
I have my grafana outside of azure which i s running in a docker container. I am working on the configuring the datasource. Followed all the steps provided by azure to monitor the vm's in gafana.
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal 

I am getting the below error in grafana:

1. Azure Monitor: Bad Gateway: Cannot connect to Azure Monitor REST API.

Can someone help on this issue.

**Comment by srudos** [comment] 2018-04-11 20:01
Bad Gateway usually means network connectivity issue. Is the Docker host behind a firewall? Are you able to connect to the following Azure URLs from inside the container?
https://management.azure.com
https://api.applicationinsights.io

**Comment by aravindrd23** [comment] 2018-04-11 20:30
No I am not able to hit those url's. My grafana don't have a public IP..

**Comment by srudos** [comment] 2018-04-12 01:46
I think this is a duplicate of #34 . Adding proxy support should resolve the issue.

**Comment by daniellee** [comment] 2018-04-13 08:00
I agree with @srudos - not much the plugin can do to help you here if you do not have access to Azure from the Grafana server.

**Closed by daniellee** 2018-04-13 08:00 UTC
