### ISSUE TITLE
Support for Template Queries

### ISSUE THREAD

**Issue by alhardy** [grafana/azure-monitor-datasource#33] opened 2018-01-25 14:01 UTC
It would be great to include support for query type variables in template on resource groups etc allowing "generic" web app dashboards to be designed for example.

Great work so far! 👍

**Comment by daniellee** [comment] 2018-02-06 12:26
Duplicate of #4 so closing this. Will hopefully have something working this week.

**Closed by daniellee** 2018-02-06 12:26 UTC
